apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: immich-canary
type: Opaque
stringData:
  accesskey: {{ .Values.minio.accessKey | quote }}
  secretkey: {{ .Values.minio.secretKey | quote }}
