apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: data-pipeline
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  accesskey: {{ .Values.minio.accessKey | quote }}
  secretkey: {{ .Values.minio.secretKey | quote }}
